name: analysis-node
services:
  resp-cap-assess:
    build:
      context: ./resp-cap-assess
    container_name: resp-cap-assess
    networks:
      - analysis-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KEYCLOAK_BASE_URL: ${KEYCLOAK_BASE_URL}
      REALM: ${REALM}
      ANALYTICS_CLIENT_ID: ${ANALYTICS_CLIENT_ID}
      ANALYTICS_CLIENT_SECRET: ${ANALYTICS_CLIENT_SECRET}
      FHIR_SERVER: ${FHIR_SERVER}
      KAFKA_USERNAME: ${KAFKA_USERNAME}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD}
      
networks:
  analysis-network:
  
